<?php

/**
 * Implementation of hook_menu().
 */
function engage_menu() {
  $items['engage'] = array(
    'title' => 'Engage',
    'page callback' => 'engage_page',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  return $items;
}

function engage_node_info(){
  return array('engage' => array(
    'title' => 'Tracked Twitter Engagement',
  ));
}

function engage_view($node, $teaser = FALSE, $page = FALSE) {
  $node->content['hello'] = array('#value' => 'hello');
  return node_prepare($node, $teaser);
}

function engage_cron() {
  engage_page();
}

function engage_pattern_count($pattern) {
  $result = db_query("select screen_name, count(twitter_id) from twitter where text $pattern group by screen_name;");
  while($b = db_fetch_array($result)) {
    $matches[$b['screen_name']] = $b['count'];
  }
  return $matches;
}

function engage_page() {
//     module_load_include('inc', 'twitter');
// 
//   $account['uid'] =1;
// 
//   $mps = array(
//     'PaulQuinnMP',
//     'GarethMP',
//     'StuartNashMP',
//     'MaungakiekieSAM',
//     'SWSio',
//     'rogerdouglas',
//     'rodneyhide',
//     'LynnePillay',
//     'jcolemanmp',
//     'JackieBlueMP',
//     'CJTremain',
//     'ChrisAuchinvole',
//     'ChesterBorrows',
//     'carmelsepuloni',
//     'aarongilmore',
//     'DarienFenton',
//     'HeatherRoyMP',
//     'DavidShearerMP',
//     'amyadamsMP',
//     'DavidClendon',
//     'chrisfinlayson',
//     'nikkikaye',
//     'katrinashanks',
//     'LianneDalzielMP',
//     'hondavidcarter',
//     'jacindaardern',
//     'MoanaMackey',
//     'darrenhughesmp',
//     'metiria',
//     'leesgallowaymp',
//     'grantrobertson1',
//     'chrishipkins',
//     'annettekingmp',
//     'phil_goff',
//     'greencatherine',
//     'KeithLocke',
//     'clarecurranmp',
//     'johnkeypm',
//     'CraigFossMP',
//     'RusselNorman',
//     'KevinHague',
//     'charleschauvel',
//     'PhilTwyford',
//     'LouiseUpston',
// 'KennedyGraham',
// 'SusieKew',
//   );
//   
//   foreach($mps as $name) {
//     $account['screen_name'] = $name;
//     twitter_user_save($account, true);
//     drupal_set_message($name);
// //     twitter_cache_account
//   }
//   return '';
  

  $result = db_query("SELECT * FROM {twitter_account}");
  $output = '';

  $retweets = engage_pattern_count(" like 'RT %'");
  $engage = engage_pattern_count(" like '%@%'");
  $broadcast = engage_pattern_count("not like '%@%'");


  while ($account = db_fetch_array($result)) {
    $e = $engage[$account['screen_name']];
    $b = $broadcast[$account['screen_name']];
    $rt = $retweets[$account['screen_name']];
    $total = $e+$b;
    
    if ($total) 
    $percent_engage = ($e / $total) * 100;
    else
    $percent_engage = 0;
      
    $rows[] = array(
//       l('user', 'user/'. $account['uid']),
      l($account['screen_name'], 'http://www.twitter.com/' . $account['screen_name']),
      t($account['description']),
//       l('node', 'node/'. $node->nid),
      $rt, $e, $b, sprintf('%.2f%%', $percent_engage),
    );
  }
  $headers = array('Name', '', 'ReTweets', 'Replies/mentions', 'Broadcasts', 'Percentage Interaction');

  $output .= theme('table', $headers, $rows);

  return $output;
}