<?php

function engage_schema() {
  $schema['engage_users'] = array(
    'fields' => array(
      'uid' => array('type' => 'int', 'not null' => TRUE),
      'reply_count' => array('type' => 'int', 'default' => 0),
    ),
    'primary key' => array('uid'),
    
  );
  return $schema;
}

function engage_install() {
  drupal_install_schema('engage');
}

function engage_unstall() {
  drupal_install_schema('engage');
}