<?php

/**
 * Implementation of hook_menu().
 */
function engage_menu() {
  $items['engage'] = array(
    'title' => 'Engage',
    'page callback' => 'engage_page',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  return $items;
}

function engage_cron() {
  engage_cache();
}

function engage_pattern_count($pattern) {
  $result = db_query("select screen_name, count(twitter_id) from twitter where text $pattern group by screen_name;");
  while($b = db_fetch_array($result)) {
    $matches[$b['screen_name']] = $b['count'];
  }
  return $matches;
}

function engage_data_load() {
    module_load_include('inc', 'twitter');

  $account['uid'] =1;

  $mps = array(
    'PaulQuinnMP',
    'GarethMP',
    'StuartNashMP',
    'MaungakiekieSAM',
    'SWSio',
    'rogerdouglas',
    'rodneyhide',
    'LynnePillay',
    'jcolemanmp',
    'JackieBlueMP',
    'CJTremain',
    'ChrisAuchinvole',
    'ChesterBorrows',
    'carmelsepuloni',
    'aarongilmore',
    'DarienFenton',
    'HeatherRoyMP',
    'DavidShearerMP',
    'amyadamsMP',
    'DavidClendon',
    'chrisfinlayson',
    'nikkikaye',
    'katrinashanks',
    'LianneDalzielMP',
    'hondavidcarter',
    'jacindaardern',
    'MoanaMackey',
    'darrenhughesmp',
    'metiria',
    'leesgallowaymp',
    'grantrobertson1',
    'chrishipkins',
    'annettekingmp',
    'phil_goff',
    'greencatherine',
    'KeithLocke',
    'clarecurranmp',
    'johnkeypm',
    'CraigFossMP',
    'RusselNorman',
    'KevinHague',
    'charleschauvel',
    'PhilTwyford',
    'LouiseUpston',
'KennedyGraham',
'SusieKew',
  );

  foreach($mps as $name) {
    $account['screen_name'] = $name;
    twitter_user_save($account, true);
    drupal_set_message($name);
//     twitter_cache_account
  }
  return '';
}  
function engage_cache() {

  $result = db_query("SELECT * FROM {twitter_account}");
  $output = '';

  $retweets = engage_pattern_count(" like 'RT %'");
  $engage = engage_pattern_count(" like '%@%' AND lower(text) NOT LIKE '%@redalert'");
  $broadcast = engage_pattern_count("not like '%@%'");

  db_query("TRUNCATE TABLE {engage_cache}");

  while ($account = db_fetch_array($result)) {
    $e = $engage[$account['screen_name']];
    $b = $broadcast[$account['screen_name']];
    $rt = $retweets[$account['screen_name']];

/*      
    $rows[] = array(
//       l('user', 'user/'. $account['uid']),
      l($account['screen_name'], 'http://www.twitter.com/' . $account['screen_name']),
      t($account['description']),
//       l('node', 'node/'. $node->nid),
      $rt, $e, $b, sprintf('%.2f%%', $percent_engage),
    );*/
    db_query("INSERT INTO {engage_cache} (screen_name, replies, retweets, broadcasts) VALUES ('%s', %d, %d, %d)", $account['screen_name'], $e, $rt, $b);
  }

  $output .= theme('table', $headers, $rows);

  return $output;
}

function engage_page() {
  engage_cache();
  $headers = array(
    array('data' => 'Name', 'field' => 'screen_name'),
    '',
    array('data' => 'ReTweets', /*'field'=> 'retweets'*/),
    array('data' => 'Replies/mentions', /*'field' => 'replies',*/ 'sort' => 'desc'),
    'Broadcasts', 'Percentage Interaction');
  $result= db_query("SELECT e.*, t.description FROM {engage_cache} e INNER JOIN {twitter_account} t ON e.screen_name = t.screen_name" . tablesort_sql($headers));
  while($r = db_fetch_object($result)) {
    $total = $r->replies + $r->broadcasts;

    if ($total) $percent_engage = ($r->replies  / $total) * 100;
    else $percent_engage = 0;

    $rows[] = array(
    l($r->screen_name, 'http://twitter.com/'. $r->screen_name),
    $r->description, $r->retweets, $r->replies, $r->broadcasts, sprintf('%.2f%%', $percent_engage));
  }
  echo theme('table', $headers, $rows); exit;
  
}