<?php
// $Id: twitter.module,v 1.2 2008/06/08 04:48:33 walkah Exp $

/**
 * Implementation of hook_meu()
 */
function twitter_menu() {
  $items = array();

  $items['admin/settings/twitter'] = array(
    'title' => 'Twitter setup',
    'description' => 'Twitter module settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('twitter_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'twitter.pages.inc'
  );

  $items['user/%user/edit/twitter'] = array(
    'title' => 'Twitter accounts',
    'page callback' => 'twitter_user_settings',
    'page arguments' => array(1),
    'access arguments' => array('add twitter accounts'),
    'weight' => 10,
    'file' => 'twitter.pages.inc',
    'type' => MENU_LOCAL_TASK,
  );
  
  return $items;
}

/**
 * Implementation of hook_perm()
 */
function twitter_perm() {
  array(
    'add twitter accounts'
  );
}

/**
 * Implementation of hook_form_alter().
 */
function twitter_form_alter(&$form, $form_state, $form_id) {
  module_load_include('inc', 'twitter');

  if (substr($form_id, -10) == '_node_form') {
    $twitter_form = twitter_form();
    if (!$twitter_form) {
      return;
    }
    $form['twitter'] = array(
      '#type' => 'fieldset',
      '#title' => t('Post to twitter.com'),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
      '#tree' => TRUE,
    );
    $form['twitter']['post'] = array(
      '#type' => 'checkbox',
      '#title' => t('Announce this post on Twitter'),
      '#default_value' => (empty($form['nid']['#value'])),
      '#id' => 'twitter-toggle',
    );
    $form['twitter'] += $twitter_form;
    $form['twitter']['status']['#default_value'] = variable_get('twitter_default_format', 'New post: !title (!url)');
    $form['twitter']['status']['#description'] = t('The given text will be posted to twitter.com. You can use !url, !title and !user as replacement text.');
  } 
}

function twitter_nodeapi(&$node, $op, $a1) {
  module_load_include('inc', 'twitter');
  
  switch ($op) {
    case 'insert':
    case 'update':
      if ($node->status && $node->twitter['post']) {
        $twitter_accounts = twitter_get_user_accounts($node->uid);
        $replacements = array('!title' => $node->title,
                              '!url' => url('node/'. $node->nid, array('absolute' => TRUE)),
                              '!user' => $node->name);
        $status = strtr($node->twitter['status'], $replacements);
        $pass = $twitter_accounts[$node->twitter['account']]['password'];
        twitter_set_status($node->twitter['account'], $pass, $status);
        drupal_set_message(t('Successfully posted to Twitter'));
      }
      break;
  }
}